<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>521ea018-1f9a-401b-ba2a-b45c045f81c1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Search.Documents" Version="12.0.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="OpenAI" Version="2.13.0" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RAGA.Application\RAGA.Application.csproj" />
    <ProjectReference Include="..\RAGA.Domain\RAGA.Domain.csproj" />
  </ItemGroup>

</Project>
